#+title: TAREA 1

*Programación*
*Fernanda Sánchez*, *Miguel Piña*

* Preguntas

1) ¿Qué es una expresión regular?, ¿cuál su definición formal?, ¿cuáles son sus
   reglas de sintaxis?

2) Define y explica qué es una Gramatica Formal.

3) ¿Cuál sería una gramatica formal para las expresiones aritméticas definida en
   forma BNF?

4) Escribe el algoritmo para convertir un número en base b a base h.

5) Escribe el algoritmo general para sumar dos números en base b.

6) ¿Qué es lo que se conoce como la arquitectura de Von Newmann y cómo esta
   compuesta?

7) Describe un desastre causado por errores artiméticos computacionales (además
   del Y2K).

8) ¿Qué significa programar y qué es un programa? Explícalo con tus propias
   palabras.

9) Además de las convenciones y el estilo de código vistas en clase, nombra y
   describe (con ejemplos) al menos 5 convenciones ó estilos de
   codificación. (Hint: PEP 8).

10) Biblioteca de Libros.

El bibliotecario local nos ha pedido que escribamos un nuevo programa de
catálogo de tarjetas porque su antiguo programa es feo y anticuado.
Eso no nos da mucho detalle, pero antes de empezar a pedir más información,
consideremos lo que ya sabemos sobre los catálogos de la biblioteca.

Los catálogos contienen listas de libros. La gente los busca para encontrar
libros sobre ciertos temas, con títulos específicos, o por un autor en
particular.
Los libros pueden ser identificados de manera única por el Número de Libro
Estándar Internacional (ISBN).
Cada libro tiene asignado un número Dewey Decimal System (DDS) para encontrarlo
en un estante en particular y cualquier autor puede estar asociado con varios
libros.

Luego, nos reunimos con el bibliotecario y nos dice que las bibliotecas no
sirven sólo para libros, también tienen DVDs, revistas y CDs, ninguno de los
cuales tiene un número ISBN o DDS. Estos tipos de elementos pueden ser
identificados de forma única por un número de PC.

El bibliotecario explica que cada tipo está organizado de una manera diferente:
- Los CDs son en su mayoría libros de audio, y sólo tienen un par de docenas en
  stock, por lo que están organizados por el apellido del autor.
- Los DVDs se dividen en género y se organizan por título.
- Las revistas se organizan por título y, a continuación, se indican por el
  número de volumen y emisión.
- Los libros son organizados por el número DDS.


Lo que quiero que me muestren es el modelado de Alto Nivel de un sistema para el
Catalogo de la Biblioteca, con un análisis extensivo y detallado de su diseno.

- ¿Cuáles son los objetos?
- ¿Qué atributos y funciones tiene cada uno?
- ¿Cómo se relacionan entre ellos?
- ¿Existen relaciones de herencia, agregación, composición? Si/No y ¿por que?
- ¿Hay funciones polimórficas o interfaces? Si/No y por que?
- Anotaciones adicionales, etc.
- Entre otras cosas.
- El modelado de clases deberá estar en un formato de Tarjetas de
  Responsabilidades como las vistas en clase.

Recuerden que si su sistema parece un spaguetti todo revuelto y complejo seguro
algo no esta bien. Siempre opten por relaciones simples y diseños
elegantes. (Aplica para todo tipo de relaciones, incluyendo amorosas y
familiares).

Hint: Si su diseno tiene más de 10 clases, piensenlo otra vez.

* Entregables

Deberán entregar un archivo llamado <NombreApellido>-tarea1.pdf y enviarlo al
correo fernanda@ciencias.unam.mx con Subject: "Programacion T1"

* Fecha de entrega

01 de Marzo 2017

* Notas

Notas:
- La tarea es personal y sobra decir que tareas copiadas serán anuladas.
- El 03 de Marzo 2017 eligiré al azar un par de personas para que defiendan su
  tarea frente al grupo y la discutamos juntos. Preparense y no falten.
- No habrá prórroga de entrega.
