* Examen 2: Programación
#+author: Fernanda Sanchez, Miguel Piña

** Transcripción de Proteinas

Se trata de una versión simplificada del proceso de transcripción de proteínas.

*** Fondo

Este proyecto es una implementación del proceso de transcripción de proteínas en
una versión simplificada.  La versión corta (desde el punto de vista
computacional) es esta.  Un largo proceso biológico traduce cadenas de ADN en
los aminoácidos, y esta secuencia de aminoácidos es lo que hace proteínas.  El
"lenguaje" del ADN es una secuencia de una de cuatro bases: adenina, timina,
guanina, citosina que se acortan generalmente a ATGC, respectivamente.

La secuencia de ATGC codificada en el ADN es el código genético descubierto por
Watson y Crick en 1953.  El proceso de transcripción comienza leyendo la
secuencia de ADN en grupos de tres, llamados codones.  Cada codón, cada
secuencia de tres bases de ADN, codifica uno de los 20 aminoácidos que son la
base para todas las proteínas.  También hay dos codones de control, un codón
START, que comienza la transcripción, y algunos codones STOP, que terminan la
transcripción.

Para que esto suceda, se necesita una tabla que traduce los aminoácidos en
codones (y potencialmente, viceversa).  Si se examina esa tabla, se representan
las 64 combinaciones de las cuatro bases como codones (4 * 4 * 4) Y algunos de
los aminoácidos están codificados por múltiples codones.

En resumen, el proceso de transcripción toma una secuencia de bases de ADN y
produce una secuencia de aminoácidos.  Deberan escribir un programa de Python
que haga esa transcripción.


*** Algoritmo Basico:
1. Leer un codon
2. Mapearlo con su correspondiente nombre en la tabla
3. Imprimir el nombre


*** Requerimientos:
Crear una clase, llamada Transcriptor, que hará el proceso de transcripción. Se codifica de la siguiente manera:

1. Leer del archivo el aminoácido a Codón. La tabla proporcionada, llamada codonTable.txt, tiene el siguiente formato:
   a. Cada línea representa un aminoácido o un comando de transcripción.
      El formato de línea tiene campos separados por el espacio, que están en orden:
	 - Nombre de la proteína triName Una-letra-nombre Lista-Codones

2. Proporcionar un método llamado transcribir.
   - La transcripción funciona de la siguiente manera:
   - Lea la cadena de ADN hasta que se lea el codón START.
   - Para cada codón, traducir el codón en su aminoácido triName.
     Por ejemplo, si usted lee el codón CAG, puede ver desde la entrada de la tabla:
     Glutamine Glu Q CAA CAG
     El codón CAG se traduce al triName Glu.
   - Continuar leyendo hasta que termine la cadena de ADN o se lea el codón STOP.

3. Una cosa extraña. En la traducción biológica común (es decir, utilizando la tabla proporcionada),
   el codón START es el mismo que el codón de metionina (met). Cuando comienza la
   lectura, ese codón codifica START.  Después que comienza la transcripción, el
   codón codifica para la metionina (met).

4. El transcriptor debe imprimir un error si:
   a. No lee un codón de la cadena (es decir, hay menos de tres bases de ADN al final de la cadena si la transcripción todavía está en proceso)
   b. Si la cadena de ADN termina y la transcripción nunca comenzo.
   c. Si la cadena de ADN termina y la transcripción nunca termino.


*** Información

1. Su programa debe ser capaz de trabajar con cualquier tabla correctamente
   codificada. La tabla asociada se encuentra en el siguiente [[file:codonTable.txt][archivo.]]
2. La parte de la cadena de ADN antes del START es irrelevante, al igual que la parte de la cadena de ADN después de la de STOP
3. Su programa deberá poder recibir como parametro de ejecucion la cadena a comprobar. Por ejemplo: python examen2.py AAAAAAAA


*** Entregables:

- Deberan entregar un archivo examen2.py con el codigo fuente de su
  solucion. Asegurencen de incluir nombre de los participantes y comentarios de
  código. Se envía al correo de fernanda@ciencias.unam.mx

*** Fecha de entrega

20 de abril del 2017 antes de 23:59
